//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XiaohaiCurator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XiaohaiCurator.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xiaohai Curator.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agent for XiaohaiCurator.
        /// </summary>
        public static string BackgroundTaskDescription {
            get {
                return ResourceManager.GetString("BackgroundTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girls Stream.
        /// </summary>
        public static string BeautyStreamTitle {
            get {
                return ResourceManager.GetString("BeautyStreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Girls.
        /// </summary>
        public static string DailyGirlTitle {
            get {
                return ResourceManager.GetString("DailyGirlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        public static string LayoutButtonGridText {
            get {
                return ResourceManager.GetString("LayoutButtonGridText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string LayoutButtonListText {
            get {
                return ResourceManager.GetString("LayoutButtonListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Girl-of-Today ....
        /// </summary>
        public static string LoadingDailyText {
            get {
                return ResourceManager.GetString("LoadingDailyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lockscreen.
        /// </summary>
        public static string LockscreenButtonText {
            get {
                return ResourceManager.GetString("LockscreenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings....
        /// </summary>
        public static string MainPageAppBarSettings {
            get {
                return ResourceManager.GetString("MainPageAppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read content through Internet now! Please check the network status and try again later..
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error.
        /// </summary>
        public static string NetworkErrorCaption {
            get {
                return ResourceManager.GetString("NetworkErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string PhotoViewerPageAppBarShare {
            get {
                return ResourceManager.GetString("PhotoViewerPageAppBarShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture is saved..
        /// </summary>
        public static string SavePictureDoneText {
            get {
                return ResourceManager.GetString("SavePictureDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture is set to lockscreen..
        /// </summary>
        public static string SetLockScreenDoneText {
            get {
                return ResourceManager.GetString("SetLockScreenDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string SettingsPageGeneralHeader {
            get {
                return ResourceManager.GetString("SettingsPageGeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock screen.
        /// </summary>
        public static string SettingsPageLockScreenHeader {
            get {
                return ResourceManager.GetString("SettingsPageLockScreenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock screen settings.
        /// </summary>
        public static string SettingsPageLockScreenHint {
            get {
                return ResourceManager.GetString("SettingsPageLockScreenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string SettingsPageLockScreenPeriodicalSwitchContentChecked {
            get {
                return ResourceManager.GetString("SettingsPageLockScreenPeriodicalSwitchContentChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string SettingsPageLockScreenPeriodicalSwitchContentUnchecked {
            get {
                return ResourceManager.GetString("SettingsPageLockScreenPeriodicalSwitchContentUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to periodically update.
        /// </summary>
        public static string SettingsPageLockScreenPeriodicalSwitchHeader {
            get {
                return ResourceManager.GetString("SettingsPageLockScreenPeriodicalSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to share you the pretty girl..
        /// </summary>
        public static string SettingsPageShareLinkMessageDefault {
            get {
                return ResourceManager.GetString("SettingsPageShareLinkMessageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Link Message.
        /// </summary>
        public static string SettingsPageShareLinkMessageTitle {
            get {
                return ResourceManager.GetString("SettingsPageShareLinkMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xiaohai Curator - Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    }
}
